name: gate_level_testing
on: [push, workflow_dispatch]

jobs:
  gl_test:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: GL test
        uses: Eragbiscool/PWM_Timer_Counter/.github/workflows/gls.yaml
        with:
          pdk: sky130
